### ISSUE TITLE
change between classes

### ISSUE THREAD

**Issue by M1chaCH** [moreach/teachu-client#47]
This issue is currently only in the feature/general-ui branch.  

1. open class using menu-tree
2. select other class using menu-tree
3. url changes but page does not update
4. reload page and page updates

**Comment by M1chaCH** [comment]
& every time when the menu-tree "re-opens" the classes are duplicated / fetched again

**Comment by M1chaCH** [comment]
> & every time when the menu-tree "re-opens" the classes are duplicated / fetched again

fixed

**Comment by M1chaCH** [comment]
> This issue is currently only in the feature/general-ui branch.
> 
> 1. open class using menu-tree
> 2. select other class using menu-tree
> 3. url changes but page does not update
> 4. reload page and page updates

@EricWermelinger do you know this issue? The routes are built exactly like your chat routes

**Comment by EricWermelinger** [comment]
As far as I understand, it happens because the Component is not reloaded when navigating to a new url from the same activated component on.

I think something like this should resolve the problem:
this.classList$ = this.router.events.pipe(
            filter(e => e instanceof NavigationEnd),
            switchMap(_ => this.service.getClass$(this.className)),
        );
in ClassListComponent instead of: this.classList$ = this.service.getClass$(this.className)),

However, I don't have my notebook currently with me, so I wasnt able to test.

**Comment by EricWermelinger** [comment]
Fixed in https://github.com/moreach/teachu-client/pull/51

**Comment by M1chaCH** [comment]
thx 👌
